// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: simple.proto
// Protobuf Java Version: 4.27.3

package com.clickhouse.test.proto;

public final class SimpleProto {
  private SimpleProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 3,
      /* suffix= */ "",
      SimpleProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SimpleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.clickhouse.test.proto.Simple)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 intField = 1;</code>
     * @return The intField.
     */
    int getIntField();

    /**
     * <code>int64 longField = 2;</code>
     * @return The longField.
     */
    long getLongField();

    /**
     * <code>float floatField = 3;</code>
     * @return The floatField.
     */
    float getFloatField();

    /**
     * <code>double doubleField = 4;</code>
     * @return The doubleField.
     */
    double getDoubleField();

    /**
     * <code>bool booleanField = 5;</code>
     * @return The booleanField.
     */
    boolean getBooleanField();

    /**
     * <code>string stringField = 6;</code>
     * @return The stringField.
     */
    java.lang.String getStringField();
    /**
     * <code>string stringField = 6;</code>
     * @return The bytes for stringField.
     */
    com.google.protobuf.ByteString
        getStringFieldBytes();
  }
  /**
   * Protobuf type {@code com.clickhouse.test.proto.Simple}
   */
  public static final class Simple extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.clickhouse.test.proto.Simple)
      SimpleOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 3,
        /* suffix= */ "",
        Simple.class.getName());
    }
    // Use Simple.newBuilder() to construct.
    private Simple(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Simple() {
      stringField_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.clickhouse.test.proto.SimpleProto.internal_static_com_clickhouse_test_proto_Simple_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.clickhouse.test.proto.SimpleProto.internal_static_com_clickhouse_test_proto_Simple_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.clickhouse.test.proto.SimpleProto.Simple.class, com.clickhouse.test.proto.SimpleProto.Simple.Builder.class);
    }

    public static final int INTFIELD_FIELD_NUMBER = 1;
    private int intField_ = 0;
    /**
     * <code>int32 intField = 1;</code>
     * @return The intField.
     */
    @java.lang.Override
    public int getIntField() {
      return intField_;
    }

    public static final int LONGFIELD_FIELD_NUMBER = 2;
    private long longField_ = 0L;
    /**
     * <code>int64 longField = 2;</code>
     * @return The longField.
     */
    @java.lang.Override
    public long getLongField() {
      return longField_;
    }

    public static final int FLOATFIELD_FIELD_NUMBER = 3;
    private float floatField_ = 0F;
    /**
     * <code>float floatField = 3;</code>
     * @return The floatField.
     */
    @java.lang.Override
    public float getFloatField() {
      return floatField_;
    }

    public static final int DOUBLEFIELD_FIELD_NUMBER = 4;
    private double doubleField_ = 0D;
    /**
     * <code>double doubleField = 4;</code>
     * @return The doubleField.
     */
    @java.lang.Override
    public double getDoubleField() {
      return doubleField_;
    }

    public static final int BOOLEANFIELD_FIELD_NUMBER = 5;
    private boolean booleanField_ = false;
    /**
     * <code>bool booleanField = 5;</code>
     * @return The booleanField.
     */
    @java.lang.Override
    public boolean getBooleanField() {
      return booleanField_;
    }

    public static final int STRINGFIELD_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object stringField_ = "";
    /**
     * <code>string stringField = 6;</code>
     * @return The stringField.
     */
    @java.lang.Override
    public java.lang.String getStringField() {
      java.lang.Object ref = stringField_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stringField_ = s;
        return s;
      }
    }
    /**
     * <code>string stringField = 6;</code>
     * @return The bytes for stringField.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStringFieldBytes() {
      java.lang.Object ref = stringField_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stringField_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (intField_ != 0) {
        output.writeInt32(1, intField_);
      }
      if (longField_ != 0L) {
        output.writeInt64(2, longField_);
      }
      if (java.lang.Float.floatToRawIntBits(floatField_) != 0) {
        output.writeFloat(3, floatField_);
      }
      if (java.lang.Double.doubleToRawLongBits(doubleField_) != 0) {
        output.writeDouble(4, doubleField_);
      }
      if (booleanField_ != false) {
        output.writeBool(5, booleanField_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(stringField_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, stringField_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (intField_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, intField_);
      }
      if (longField_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, longField_);
      }
      if (java.lang.Float.floatToRawIntBits(floatField_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, floatField_);
      }
      if (java.lang.Double.doubleToRawLongBits(doubleField_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, doubleField_);
      }
      if (booleanField_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, booleanField_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(stringField_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, stringField_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.clickhouse.test.proto.SimpleProto.Simple)) {
        return super.equals(obj);
      }
      com.clickhouse.test.proto.SimpleProto.Simple other = (com.clickhouse.test.proto.SimpleProto.Simple) obj;

      if (getIntField()
          != other.getIntField()) return false;
      if (getLongField()
          != other.getLongField()) return false;
      if (java.lang.Float.floatToIntBits(getFloatField())
          != java.lang.Float.floatToIntBits(
              other.getFloatField())) return false;
      if (java.lang.Double.doubleToLongBits(getDoubleField())
          != java.lang.Double.doubleToLongBits(
              other.getDoubleField())) return false;
      if (getBooleanField()
          != other.getBooleanField()) return false;
      if (!getStringField()
          .equals(other.getStringField())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INTFIELD_FIELD_NUMBER;
      hash = (53 * hash) + getIntField();
      hash = (37 * hash) + LONGFIELD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLongField());
      hash = (37 * hash) + FLOATFIELD_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getFloatField());
      hash = (37 * hash) + DOUBLEFIELD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getDoubleField()));
      hash = (37 * hash) + BOOLEANFIELD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getBooleanField());
      hash = (37 * hash) + STRINGFIELD_FIELD_NUMBER;
      hash = (53 * hash) + getStringField().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.clickhouse.test.proto.SimpleProto.Simple parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.clickhouse.test.proto.SimpleProto.Simple parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.clickhouse.test.proto.SimpleProto.Simple parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.clickhouse.test.proto.SimpleProto.Simple parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.clickhouse.test.proto.SimpleProto.Simple parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.clickhouse.test.proto.SimpleProto.Simple parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.clickhouse.test.proto.SimpleProto.Simple parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.clickhouse.test.proto.SimpleProto.Simple parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.clickhouse.test.proto.SimpleProto.Simple parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.clickhouse.test.proto.SimpleProto.Simple parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.clickhouse.test.proto.SimpleProto.Simple parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.clickhouse.test.proto.SimpleProto.Simple parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.clickhouse.test.proto.SimpleProto.Simple prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.clickhouse.test.proto.Simple}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.clickhouse.test.proto.Simple)
        com.clickhouse.test.proto.SimpleProto.SimpleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.clickhouse.test.proto.SimpleProto.internal_static_com_clickhouse_test_proto_Simple_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.clickhouse.test.proto.SimpleProto.internal_static_com_clickhouse_test_proto_Simple_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.clickhouse.test.proto.SimpleProto.Simple.class, com.clickhouse.test.proto.SimpleProto.Simple.Builder.class);
      }

      // Construct using com.clickhouse.test.proto.SimpleProto.Simple.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        intField_ = 0;
        longField_ = 0L;
        floatField_ = 0F;
        doubleField_ = 0D;
        booleanField_ = false;
        stringField_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.clickhouse.test.proto.SimpleProto.internal_static_com_clickhouse_test_proto_Simple_descriptor;
      }

      @java.lang.Override
      public com.clickhouse.test.proto.SimpleProto.Simple getDefaultInstanceForType() {
        return com.clickhouse.test.proto.SimpleProto.Simple.getDefaultInstance();
      }

      @java.lang.Override
      public com.clickhouse.test.proto.SimpleProto.Simple build() {
        com.clickhouse.test.proto.SimpleProto.Simple result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.clickhouse.test.proto.SimpleProto.Simple buildPartial() {
        com.clickhouse.test.proto.SimpleProto.Simple result = new com.clickhouse.test.proto.SimpleProto.Simple(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.clickhouse.test.proto.SimpleProto.Simple result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.intField_ = intField_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.longField_ = longField_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.floatField_ = floatField_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.doubleField_ = doubleField_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.booleanField_ = booleanField_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.stringField_ = stringField_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.clickhouse.test.proto.SimpleProto.Simple) {
          return mergeFrom((com.clickhouse.test.proto.SimpleProto.Simple)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.clickhouse.test.proto.SimpleProto.Simple other) {
        if (other == com.clickhouse.test.proto.SimpleProto.Simple.getDefaultInstance()) return this;
        if (other.getIntField() != 0) {
          setIntField(other.getIntField());
        }
        if (other.getLongField() != 0L) {
          setLongField(other.getLongField());
        }
        if (other.getFloatField() != 0F) {
          setFloatField(other.getFloatField());
        }
        if (other.getDoubleField() != 0D) {
          setDoubleField(other.getDoubleField());
        }
        if (other.getBooleanField() != false) {
          setBooleanField(other.getBooleanField());
        }
        if (!other.getStringField().isEmpty()) {
          stringField_ = other.stringField_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                intField_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                longField_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 29: {
                floatField_ = input.readFloat();
                bitField0_ |= 0x00000004;
                break;
              } // case 29
              case 33: {
                doubleField_ = input.readDouble();
                bitField0_ |= 0x00000008;
                break;
              } // case 33
              case 40: {
                booleanField_ = input.readBool();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 50: {
                stringField_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int intField_ ;
      /**
       * <code>int32 intField = 1;</code>
       * @return The intField.
       */
      @java.lang.Override
      public int getIntField() {
        return intField_;
      }
      /**
       * <code>int32 intField = 1;</code>
       * @param value The intField to set.
       * @return This builder for chaining.
       */
      public Builder setIntField(int value) {

        intField_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 intField = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIntField() {
        bitField0_ = (bitField0_ & ~0x00000001);
        intField_ = 0;
        onChanged();
        return this;
      }

      private long longField_ ;
      /**
       * <code>int64 longField = 2;</code>
       * @return The longField.
       */
      @java.lang.Override
      public long getLongField() {
        return longField_;
      }
      /**
       * <code>int64 longField = 2;</code>
       * @param value The longField to set.
       * @return This builder for chaining.
       */
      public Builder setLongField(long value) {

        longField_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int64 longField = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLongField() {
        bitField0_ = (bitField0_ & ~0x00000002);
        longField_ = 0L;
        onChanged();
        return this;
      }

      private float floatField_ ;
      /**
       * <code>float floatField = 3;</code>
       * @return The floatField.
       */
      @java.lang.Override
      public float getFloatField() {
        return floatField_;
      }
      /**
       * <code>float floatField = 3;</code>
       * @param value The floatField to set.
       * @return This builder for chaining.
       */
      public Builder setFloatField(float value) {

        floatField_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>float floatField = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFloatField() {
        bitField0_ = (bitField0_ & ~0x00000004);
        floatField_ = 0F;
        onChanged();
        return this;
      }

      private double doubleField_ ;
      /**
       * <code>double doubleField = 4;</code>
       * @return The doubleField.
       */
      @java.lang.Override
      public double getDoubleField() {
        return doubleField_;
      }
      /**
       * <code>double doubleField = 4;</code>
       * @param value The doubleField to set.
       * @return This builder for chaining.
       */
      public Builder setDoubleField(double value) {

        doubleField_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>double doubleField = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDoubleField() {
        bitField0_ = (bitField0_ & ~0x00000008);
        doubleField_ = 0D;
        onChanged();
        return this;
      }

      private boolean booleanField_ ;
      /**
       * <code>bool booleanField = 5;</code>
       * @return The booleanField.
       */
      @java.lang.Override
      public boolean getBooleanField() {
        return booleanField_;
      }
      /**
       * <code>bool booleanField = 5;</code>
       * @param value The booleanField to set.
       * @return This builder for chaining.
       */
      public Builder setBooleanField(boolean value) {

        booleanField_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>bool booleanField = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearBooleanField() {
        bitField0_ = (bitField0_ & ~0x00000010);
        booleanField_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object stringField_ = "";
      /**
       * <code>string stringField = 6;</code>
       * @return The stringField.
       */
      public java.lang.String getStringField() {
        java.lang.Object ref = stringField_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          stringField_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string stringField = 6;</code>
       * @return The bytes for stringField.
       */
      public com.google.protobuf.ByteString
          getStringFieldBytes() {
        java.lang.Object ref = stringField_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stringField_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string stringField = 6;</code>
       * @param value The stringField to set.
       * @return This builder for chaining.
       */
      public Builder setStringField(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        stringField_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string stringField = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearStringField() {
        stringField_ = getDefaultInstance().getStringField();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string stringField = 6;</code>
       * @param value The bytes for stringField to set.
       * @return This builder for chaining.
       */
      public Builder setStringFieldBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        stringField_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.clickhouse.test.proto.Simple)
    }

    // @@protoc_insertion_point(class_scope:com.clickhouse.test.proto.Simple)
    private static final com.clickhouse.test.proto.SimpleProto.Simple DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.clickhouse.test.proto.SimpleProto.Simple();
    }

    public static com.clickhouse.test.proto.SimpleProto.Simple getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Simple>
        PARSER = new com.google.protobuf.AbstractParser<Simple>() {
      @java.lang.Override
      public Simple parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Simple> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Simple> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.clickhouse.test.proto.SimpleProto.Simple getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_clickhouse_test_proto_Simple_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_clickhouse_test_proto_Simple_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014simple.proto\022\031com.clickhouse.test.prot" +
      "o\"\201\001\n\006Simple\022\020\n\010intField\030\001 \001(\005\022\021\n\tlongFi" +
      "eld\030\002 \001(\003\022\022\n\nfloatField\030\003 \001(\002\022\023\n\013doubleF" +
      "ield\030\004 \001(\001\022\024\n\014booleanField\030\005 \001(\010\022\023\n\013stri" +
      "ngField\030\006 \001(\tB(\n\031com.clickhouse.test.pro" +
      "toB\013SimpleProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_clickhouse_test_proto_Simple_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_clickhouse_test_proto_Simple_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_clickhouse_test_proto_Simple_descriptor,
        new java.lang.String[] { "IntField", "LongField", "FloatField", "DoubleField", "BooleanField", "StringField", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
