name: Nightly

on:
  schedule:
    - cron: "55 15 * * *"
  workflow_dispatch:
    inputs:
      pr:
        description: "Pull request#"
        required: false
jobs:
  nightly:
    if: ${{ startsWith(github.repository, 'ClickHouse/') }}
    name: "Test Nightly"
    runs-on: "ubuntu-latest"
    timeout-minutes: 20
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.CHC_BRANCH }}
      - name: Check out PR
        run: |
          git fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 \
            origin pull/${{ github.event.inputs.pr }}/merge:merged-pr && git checkout merged-pr
        if: github.event.inputs.pr != ''
      - name: Install JDK and Maven
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: |
            8
            17
          cache: 'maven'
      - name: Setup Toolchain
        shell: bash
        run: |
          mkdir -p $HOME/.m2 \
          && cat << EOF > $HOME/.m2/toolchains.xml
          <?xml version="1.0" encoding="UTF8"?>
          <toolchains>
            <toolchain>
              <type>jdk</type>
              <provides>
                <version>17</version>
              </provides>
              <configuration>
                <jdkHome>${{ env.JAVA_HOME }}</jdkHome>
              </configuration>
            </toolchain>
          </toolchains>
          EOF
      - name: Test Java client
        env:
          CLICKHOUSE_CLOUD_HOST: ${{ secrets.INTEGRATIONS_TEAM_TESTS_CLOUD_HOST_SMT }}
          CLICKHOUSE_CLOUD_PASSWORD: ${{ secrets.INTEGRATIONS_TEAM_TESTS_CLOUD_PASSWORD_SMT }}
        run: |
          mvn -DCLICKHOUSE_HOSTNAME=${{ secrets.INTEGRATIONS_TEAM_TESTS_CLOUD_HOST_SMT }} -DCLICKHOUSE_PASSWORD=${{ secrets.INTEGRATIONS_TEAM_TESTS_CLOUD_PASSWORD_SMT }} test
